выполняет д/з модуляция
htmlacademy-javascript/1916801-kekstagram-25 pull request #4
Opened 2022-03-10 10:37 UTC by korvet07

2022-03-10 12:44 UTC, yury-dergachev commented on js/data.js
> +import { getRandomArrayElement, getRandomIntInclusive } from './util.js';
Тут все верно. 

Но для справки. Удобнее было бы импортировать через *, функция может быть очень много и тогда тут будет громадное полотно )

`import * as util from './util.js';`

использовать тогда так 

```
util.getRandomArrayElement()
util.getRandomIntInclusive()
```

2022-03-10 12:46 UTC, ydergachev commented on js/data.js
> +const collectionDescriptionsFoto = () => Array.from({ length: COLLECTION_DESCRIPTIONS }, createDescriptionsFoto);
`collectionDescriptionsFoto` надо переименовать функцию. Назвать с глаголом, т.к эта функция делает действие, а именно возвращает структуру моковых данных. 
используй вначале get или сreate

например getMockPhotos
createMockPhotos и т.д

2022-03-10 12:47 UTC, ydergachev commented on js/util.js
> +checkLengthString('строка');
`checkLengthString('строка');` - надо убрать. Тут уже не нужен этот вызов. 

`export const getRandomArrayElement = (element) => element[getRandomIntInclusive(0, element.length - 1)];` - можно сразу экспортировать функцию из модуля, не плодя внизу полотно из экспортов)

2022-03-10 13:14 UTC, korvet07 commented on js/data.js
> +import { getRandomArrayElement, getRandomIntInclusive } from './util.js';
Ага, вот про * обещали рассказать- теперь понятно

2022-03-12 07:54 UTC, ydergachev commented on js/util.js
> +  }
`return null;` Тут нельзя возвращать null, т.к если выполнится это условия и из функции вернется не число, а мы всегда ожидаем число, код может сломаться. Верни тут просто 0 например

2022-03-12 08:09 UTC, ydergachev commented on js/util.js
> +}
```
function createRandomCommentId (min, max) {
  const previousValues = [];
  return function () {
    let currentValue = getRandomIntInclusive(min, max);
    if (previousValues.length >= (max - min + 1)) {
      window.console.error(`Перебраны все числа из диапазона от ${ min } до ${ max }`);
      return null;
    }
    while (previousValues.includes(currentValue)) {
      currentValue = getRandomIntInclusive(min, max);
    }
    previousValues.push(currentValue);
    return currentValue;
  };
}
```

Это будет крайне избыточная фукнкция. Если задачу можно решить просто, ее надо решать просто). 
Эту функцию убери и перепиши так 

```
const createComment = (index) => {
  return   {
    id: index, 
    avatar: `img/avatar-${util.getRandomIntInclusive(1, 6)}.svg`,
    message: util.getRandomArrayElement(MESSAGE_COMMENT),
    name: util.getRandomArrayElement(NAMES),
  }
}

const createDescriptionsPhotos = () => {
  return {
    id: makeCountIdDescription(25),
    url: `photos/${makeCountValuePhotos(25)}.jpg`,
    description: 'Это мы на Гаваях)',
    likes: util.getRandomIntInclusive(15, 200),
    comments: new Array(6).fill('').map((item, index) => createComment(index)),
  }
}
```

2022-03-12 10:44 UTC, sterlikoff requested changes
Анатолий, супер, с подключением модулей разобрался.

По этому заданию только одно замечание:

 - Не очень хорошая практика `import *`. Например названия функций в модулях могут совпасть и произойдет конфликт. Лучше импортировать ровно то, что необходимо. Понятно, что сейчас мы в `data` используем все, что есть в `utils`, но `utils` мы явно будем расширять и для других модулей.

В целом по проекту еще напишу сразу тут:

- `MESSAGE_COMMENT` -> `MESSAGE_COMMENTS`
- Функции должны быть заданы одни способом, предпочтительно в стрелочном виде.
- `makeCount` переменовать так, чтобы было понятно что функция что-то возвращает, а также что именно.
- над `makeCountIdDescription` и `makeCountValuePhotos` тоже подумать, переменные не должны с глагола начинаться.
- `createComments` кажется создает один, а не несколько комментариев
- `createDescriptionsPhotos` тоже

Хороший нейминг - гора сэкономленного времени, твоего и коллег :)

2022-03-12 14:43 UTC, merged

2022-03-12 14:43 UTC, sterlikoff approved these changes
Теперь все отлично) зачет, идем дальше)